apiVersion: apps/v1
kind: Deployment
metadata:
  name: urbanestia-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: urbanestia-backend
  template:
    metadata:
      labels:
        app: urbanestia-backend
    spec:
      containers:
        - name: urbanestia-backend-container
          image: ismaeltrochas/urbanestia:latest
          ports:
            - containerPort: 8080
            - containerPort: 8081
          env:
            # Para ConfigMap
            - name: URBENESTIA_PROPERTIES_URL
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: URBENESTIA_PROPERTIES_URL
---
apiVersion: v1
kind: Service
metadata:
  name: urbanestia-service
spec:
  selector:
    app: urbanestia-backend
  ports:
    - protocol: TCP
      port: 80         # Puerto que expone el servicio
      targetPort: 8081 # Puerto del contenedor
  type: ClusterIP     # Tipo de servicio
