apiVersion: apps/v1
kind: Deployment
metadata:
  name: urbanestia-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: urbanestia-backend
  template:
    metadata:
      labels:
        app: urbanestia-backend
    spec:
      containers:
        - name: urbanestia-backend-container
          image: ismaeltrochas/urbanestia:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: urbanestia-service
spec:
  selector:
    app: urbanestia-service
  ports:
    - protocol: TCP
      port: 80         # Puerto que expone el servicio
      targetPort: 8080 # Puerto del contenedor
  type: LoadBalancer     # Tipo de servicio
