apiVersion: apps/v1
kind: Deployment
metadata:
  name: urbanestia-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: urbanestia-backend
  template:
    metadata:
      labels:
        app: urbanestia-backend
    spec:
      containers:
        - name: urbanestia-backend-container
          image: ismaeltrochas/urbanestia:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: urbanestia-service
spec:
  selector:
    app: urbanestia-backend
  ports:
    - protocol: TCP
      port: 80         # Puerto que expone el servicio de K8s
      targetPort: 8081 # Puerto del contenedor en Dockerfile o en application.yml donde se expone la API
  type: ClusterIP     # Tipo de servicio en K8s
