services:
  mongodb:
    image: 'mongo:latest'
    container_name: 'urbanestia_mongodb'
    environment:
      - 'MONGO_INITDB_DATABASE=properties_db'
      - 'MONGO_INITDB_ROOT_PASSWORD=urbanestia_ismael'
      - 'MONGO_INITDB_ROOT_USERNAME=urbanestia_properties'
    ports:
      - '27017:27017'
    networks:
       - mongo-network

  mongo-express:
    build: .
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=adminpassword
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - "8081:8081"
    networks:
      - mongo-network
    depends_on:
      - mongodb

volumes:
  mongo-data:
    driver: local

networks:
  mongo-network:
    driver: bridge