services:
  mongodb:
    image: 'mongo:latest'
    container_name: 'liquors-golden-mongodb'
    environment:
      - 'MONGO_INITDB_DATABASE=properties_db'
      - 'MONGO_INITDB_ROOT_PASSWORD=urbanestia_ismael'
      - 'MONGO_INITDB_ROOT_USERNAME=urbanestia_properties'
    ports:
      - '27017:27017'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge