spring:
  application:
    name: mcsv-property
  profiles:
    active: kubernetes
  data:
    mongodb:
      uri: mongodb://mongo:WXBLRlYRRenvTIhyjqcBxpvBXZrpEjwS@junction.proxy.rlwy.net:24993/urbanestia?authSource=admin