server:
  port: 8081

spring:
  application:
    name: properties-mcsv
  data:
    mongodb:
      uri: mongodb://mongo:WXBLRlYRRenvTIhyjqcBxpvBXZrpEjwS@junction.proxy.rlwy.net:24993/urbanestia?authSource=admin
