name: Build and Push Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        
    - name: Build project
      run: mvn clean package

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/urbanestia:${{ github.sha }} .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/urbanestia:${{ github.sha }}

    - name: Logout from DockerHub
      run: docker logout
      
    # Configurar el contexto de Kubernetes y desplegar
    - name: Set up Kubernetes context and deploy
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
        kubectl apply -f deployment.yaml
        kubectl set image deployment/urbanestia-backend urbanestia-backend-container=${{ secrets.DOCKER_USERNAME }}/urbanestia:${{ github.sha }}
