name: Build and Push Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    # Paso 2: Instalar JDK 17 (Requerido por Amazon Corretto 17)
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        
    # Paso 3: Construir el proyecto con Maven
    - name: Build project
      run: mvn clean package

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/urbanestia:${{ github.sha }} .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/urbanestia:${{ github.sha }}

    - name: Logout from DockerHub
      run: docker logout
      
      # Configurar el contexto de Kubernetes usando el secreto KUBECONFIG
    - name: Set up Kubernetes context
      run: |
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
      # Asegúrate de que el directorio .kube existe
      shell: bash

    # Actualizar el despliegue en Kubernetes
    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/urbanestia-deployment urbanestia=${{ secrets.DOCKER_USERNAME }}/urbanestia:${{ github.sha }}
